version: "3.7"
services:
  # web:
  #   image: go-clean-arch
  #   container_name: ecommerce_management_api
  #   ports:
  #     - 8080:8080
  #   depends_on:
  #     mysql:
  #       condition: service_healthy
  #   volumes:
  #     - ./config.json:/app/config.json

  mariadb:
    image: mariadb
    container_name: ecommerce
    # command: mysqld --user=root
    volumes:
      - ./migrate/colors.sql:/docker-entrypoint-initdb.d/init.sql
      - ./migrate/figures.sql:/docker-entrypoint-initdb.d/init.sql
      - ./migrate/gender.sql:/docker-entrypoint-initdb.d/init.sql
      - ./migrate/orders.sql:/docker-entrypoint-initdb.d/init.sql
      - ./migrate/pattern.sql:/docker-entrypoint-initdb.d/init.sql
      - ./migrate/products.sql:/docker-entrypoint-initdb.d/init.sql
      - ./migrate/size.sql:/docker-entrypoint-initdb.d/init.sql
      - ./migrate/status.sql:/docker-entrypoint-initdb.d/init.sql
      - ./migrate/user.sql:/docker-entrypoint-initdb.d/init.sql
      
    ports:
      - 3306:3306
    environment:
      - MYSQL_DATABASE=ecommerce
      - MYSQL_USER=root
      - MYSQL_PASSWORD=test
      - MYSQL_ROOT_PASSWORD=test

    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 5s
      retries: 10
